[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-classy" 
version = "1.4.0"
description = "A high-performance, functional asynchronous networking framework."
authors = [{ name="mk-2015", email="sxcyber17+firepy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"  
license = "MIT"
license-files = ["LICENSE*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers"
]

dependencies = [
    "aiohttp>=3.9.0",
    "asyncpg>=0.29.0",
    "aiomysql>=0.2.0",
    "aiosqlite>=0.19.0",
    "colorama>=0.4.6",
    "pydantic>=2.13.4"
]

[project.urls]
"Homepage" = "https://github.com/mk-2015/classy"
"Bug Tracker" = "https://github.com/mk-2015/classy/issues"