[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["classy"]

[project]
name = "firepy-aioclassy"
version = "1.6.0"
description = "A high-performance, functional asynchronous networking framework."
authors = [{ name="mk-2015", email="sxcyber17+firepy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"  
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers"
]

dependencies = [
    "aiohttp>=3.9.0",
    "aiosqlite>=0.19.0",
    "colorama>=0.4.6",
    "pydantic>=2.13.4"
]

[project.optional-dependencies]
postgres = ["asyncpg>=0.29.0"]
mysql = ["aiomysql>=0.2.0"]
betterauth = ["pyotp>=2.9.0", "authlib>=1.7.2"]
all = [
    "firepy-aioclassy[postgres]",
    "firepy-aioclassy[mysql]",
    "firepy-aioclassy[betterauth]"
]

[project.urls]
"Homepage" = "https://github.com/mk-2015/classy"
"Bug Tracker" = "https://github.com/mk-2015/classy/issues"